version: '3'
services:
  webapp:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: flask-mongo-app
    ports:
      - "5050:5000"
  database:
    image: "mongo:latest"
    container_name: flask-mongo-db


